trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Provider.Events.Api
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-providerevents

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.4
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks      

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  - group: TEST das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_PP
  dependsOn: Build
  displayName: Deploy to PP
  variables:
  - group: PREPROD Management Resources
  - group: PREPROD Shared Resources
  - group: PREPROD das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM

- stage: Deploy_PROD
  dependsOn: Build
  displayName: Deploy to PROD
  variables:
  - group: PROD Management Resources
  - group: PROD Shared Resources
  - group: PROD das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: PROD
      ServiceConnection: SFA-DIG-Prod-ARM

- stage: Deploy_MO
  dependsOn: Build
  displayName: Deploy to MO
  variables:
  - group: MO Management Resources
  - group: MO Shared Resources
  - group: MO das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: MO
      ServiceConnection: SFA-ASM-ModelOffice-ARM

- stage: Deploy_DEMO
  dependsOn: Build
  displayName: Deploy to DEMO
  variables:
  - group: DevTest Management Resources
  - group: DEMO DevTest Shared Resources
  - group: DEMO das-providerevents
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: DEMO
      ServiceConnection: SFA-DAS-DevTest-ARM
