parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  variables:
  - group: BUILD Management Resources
  steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.3.0'
      inputs:
        versionSpec: 4.x

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: 'src/api/SFA.DAS.Provider.Events.sln'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: restore
        projects: "src/api/**/*.csproj"   

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: 'src/api/SFA.DAS.Provider.Events.sln'
        vsVersion: 15.0
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        clean: true

    - task: VSBuild@1
      displayName: 'Publish API'
      inputs:
        solution: 'src/api/SFA.DAS.Provider.Events.Api/SFA.DAS.Provider.Events.Api.csproj'
        vsVersion: 15.0
        msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SkipInvalidConfigurations=true /p:publishUrl="$(build.artifactstagingdirectory)/SFA.DAS.Provider.Events.Api"'
        platform: 'anycpu'
        configuration: '$(buildConfiguration)'
        clean: true

    - task: ArchiveFiles@2
      displayName: 'Archive Api App'
      inputs:
        includeRootFolder: false
        rootFolderOrFile: '$(build.artifactstagingdirectory)/SFA.DAS.Provider.Events.Api'
        archiveFile: '$(build.artifactstagingdirectory)/publish/SFA.DAS.Provider.Events.Api.zip'

    - task: CopyFiles@2
      displayName: Copy Files to $(build.artifactstagingdirectory)/publish
      inputs:
        Contents: |
          azure/**
        TargetFolder: $(build.artifactstagingdirectory)/publish
        OverWrite: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact - PaymentsApi
      inputs:
        targetPath: $(build.artifactstagingdirectory)/publish
        artifactName: drop

    - template: azure-pipelines-templates/build/step/nuget-pack.yml@das-platform-building-blocks
      parameters:
        DotNetStandardPackagesToPack: |
          src/SFA.DAS.Provider.Events.Api.Client/SFA.DAS.Provider.Events.Api.Client.csproj