parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  variables:
  - group: BUILD Management Resources
  steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

    - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "src/**/*.csproj"   

    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: 'src/SFA.DAS.Provider.Events.sln'
        vsVersion: 15.0
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        clean: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: 'src/**/*.UnitTests.csproj'   

    - task: DotNetCoreCLI@2
      displayName: Publish - dotnet publish ${{ parameters.SolutionBaseName }}
      inputs:
        command: publish
        publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
        projects: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.csproj
        arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.BuildConfiguration }} --no-build
        modifyOutputPath: true
        zipAfterPublish: true

    - task: CopyFiles@2
      displayName: Copy Files to $(build.artifactstagingdirectory)/publish
      inputs:
        Contents: |
          azure/**
        TargetFolder: $(build.artifactstagingdirectory)/publish
        OverWrite: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact - PaymentsApi
      inputs:
        targetPath: $(build.artifactstagingdirectory)/publish
        artifactName: drop