parameters:  
  Environment:
  ServiceConnection:

jobs:
- deployment: DeployAPI
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SharedEnvResourceGroup: $(SharedEnvResourceGroup)
            SharedEnvVirtualNetworkName : $(SharedEnvVirtualNetworkName)
            BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
            ResourceEnvironmentName: $(ResourceEnvironmentName)
            UnrestrictedEnvironments: $(UnrestrictedEnvironments)
            UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/drop/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/drop/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              LoggingRedisConnectionString: $(LoggingConnectionString)
              ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
              ApiTokenSecret: $(ApiTokenSecret)
              PaymentsV2ConnectionString: $(PaymentsV2ConnectionString)
              EventsConnectionString: $(EventsConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-payments-api-client
            TargetFileName: '*.schema.json'
            TableName: Configuration
        - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            AppServiceName: $(AppServiceName)
            DeploymentPackagePath: $(Pipeline.Workspace)/drop/SFA.DAS.Provider.Events.Api.zip